### ISSUE TITLE
model.detect_objects take so much time

### ISSUE THREAD

**Issue by lvmy3** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#11]
when I try the code, the model.detect_objects part take much more time than training part, is that normal? I am using 4gpu, but model.detect_objects actually use only one(model.module.detect_objects), so it's very slow. Is there any possible way to improve this?

**Comment by lvmy3** [comment]
In my previous code, I defined the detect_object as an module, but probably I forgot to  send this module to gpu, my fault! I made such a stupid mistake... sorry to have bothered you guys...

**Comment by gavrilo91** [comment]
@lvmy3 Did you solved this issue? Thanks :)
