### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'BEST_checkpoint_ssd300.pth.tar'

### ISSUE THREAD

**Issue by TeerathChandani** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#15]
I can not find this model.

**Comment by ViswanathaReddyGajjala** [comment]
You can download the pre-trained model from this link.
https://drive.google.com/file/d/1YZp2PUR1NYKPlBIVoVRO0Tg1ECDmrnC3/view

**Comment by kleinash** [comment]
I download this file but I am struggling to get at the pth file. Using 7-Zip its not recognised as a tar file:

![image](https://user-images.githubusercontent.com/2494123/64278493-e0418380-cf1a-11e9-97f4-68ae0b512428.png)

On linux I use 

![image](https://user-images.githubusercontent.com/2494123/64278592-1f6fd480-cf1b-11e9-9483-546354e8e999.png)

I tried just renaming by removing the .tar - but that was just grasping at straws

**Comment by ViswanathaReddyGajjala** [comment]
No need to extract the pth file. Follow the below command for loading the model
```
model = torch.load('iNat_2018_InceptionV3.pth.tar', map_location='cpu')
#For GPU 
model = torch.load('iNat_2018_InceptionV3.pth.tar')
```

**Comment by kleinash** [comment]
Awesome thank you.

**Comment by TeerathChandani** [comment]
Thanks. :)

**Comment by shriyakak** [comment]
Can anyone please confirm where I can find the trained model checkpoint_ssd300.pth.tar ?

**Comment by shriyakak** [comment]
> You can download the pre-trained model from this link.
> https://drive.google.com/file/d/1YZp2PUR1NYKPlBIVoVRO0Tg1ECDmrnC3/view

This link is not working for me. Could you please share the link again for pre-trained model
