### ISSUE TITLE
Files are missing

### ISSUE THREAD

**Issue by amrit-das** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#2]
Please upload all the required files or mention where to download and where to place.

**Comment by sgrvinod** [comment]
Hi, the tutorial is complete now. Please see [this section](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#training) to commence training. This will save the files you need.

If you want to use an existing checkpoint in any file, you can download mine as mentioned [here](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#model-checkpoint).
