### ISSUE TITLE
train.py just stops working

### ISSUE THREAD

**Issue by gavrilo91** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#33]
Hi, 
Is there any reason why ```train.py``` script just die if I'm using CUDA as a device, and only then? If I'm running using CPU as a device it's working (but slow ofc). I have two GPUs and I've tried multiple approaches like defining exact cuda etc. Strange thing is that ```train.py``` didn't throw any error or warning message. Just dies.

**Comment by gavrilo91** [comment]
I've moved execution to the machine with only one GPU and now everything works fine. But, still I'm not sure what is the issue.

**Comment by nguyentienanh2303** [comment]
@gavrilo91 Could you show me what did you move in code?
Thanks

**Comment by bzzonly** [comment]
> I've moved execution to the machine with only one GPU and now everything works fine. But, still I'm not sure what is the issue.

I also meet the same problem. I just git clone the repo, change the path of VOC07 and 12, then run the train.py, it doesn't work.

it has this warning :
/home/anaconda3/envs/pytorch04/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))

**Comment by bzzonly** [comment]
> @gavrilo91 Could you show me what did you move in code?
> Thanks

i meet the same question

**Comment by bzzonly** [comment]
i change to pytorch1.3.0, cuda10.0, and it works

**Comment by gavrilo91** [comment]
@bzzonly same here, tnx. Updated GPU drivers and cuda to 10.0 and now it works.
