### ISSUE TITLE
good detection but poor eval (on the same dataset)

### ISSUE THREAD

**Issue by AntoineMath** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#39]
I trained the SSD on custom image dataset (1 object per image and 3 different classes)

I evaluated it on similar (but new) images ---> **mAP=0.96**
and on realy different images ---> **mAP = 0.31**

The problem comes when I use detect.py on both eval datasets:
**both give me rly good visual results (with almost no error)**

Here is the 3 different poses i'm able to detect and classify (with top_k=1):
![poses_detection](https://user-images.githubusercontent.com/44801785/73948913-e8eb1b00-48f9-11ea-9458-acde17a2f8a9.png)

This is the evaluation on different cases: 

_easy dataset, topk = 200 :_ (AP = 0.9)
![PR_lying_down_easy_dataset_topk200](https://user-images.githubusercontent.com/44801785/73950897-08d00e00-48fd-11ea-85e3-df0d755a1820.png)

_easy dataset, topk = 1 :_ (AP = 0.9)
![PR_lying_down_easy_dataset_topk1](https://user-images.githubusercontent.com/44801785/73950945-1b4a4780-48fd-11ea-8cd2-fa51225d1bcc.png)

_hard dataset, topk = 200 :_  (AP = 0.2)
![PR_lying_down_hard_dataset_topk200](https://user-images.githubusercontent.com/44801785/73950989-2dc48100-48fd-11ea-8a9f-c70056e1c3de.png)

_hard dataset, topk = 1 :_  (AP = 0.2)
![PR_lying_down_hard_dataset_topk1](https://user-images.githubusercontent.com/44801785/73951096-564c7b00-48fd-11ea-8a8d-ed931cb8efe8.png)

And for all these cases, **when I visualize images with top k = 1, I have a 0 error** (visual AP = 1)

With the debugger, I figured out that the **"lying_down" class produces a lot of false positives**, which explains the low mAP.
So it comes from a **bad jaccard intersection** (<0.5)... but I don't understand because when I detect.py, **predicted bounding boxes are realy accurate, visualy**.
So, I took only the top_k = 1 object per image in eval.py, but nothing changed : still perfect visual results and still poor mAP.
**I don't understand why by setting topk=1 in eval.py doesn't solve the false positive detection**... Tuning these parameters change nothing...

**Comment by rebeen** [comment]
could you please help me to evaluate my SSD model since I used this https://github.com/qfgaohao/pytorch-ssd 
with coco dataset and v-coco annotation now I do not know how to get the result.json  file because I have got model.pth file
