### ISSUE TITLE
can you direct me how create a jsonfile as i had run train.py it says FileNotFoundError: [Errno 2] No such file or directory: './TRAIN_images.json'

### ISSUE THREAD

**Issue by RAMACHANDRA-BABU1022** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#6]

**Comment by borre47** [comment]
In the training section
Before you begin, make sure to save the required data files for training and validation. To do this, run the contents of create_data_lists.py after pointing it to the VOC2007 and VOC2012 folders in your downloaded data.
