### ISSUE TITLE
Not able to access the pre-trained model

### ISSUE THREAD

**Issue by zackdilan** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#65]
Hi all, 

I am not able to untar the pre-trained model. Is the file corrupted? If not, please let me know how to use it?

**Comment by LukeTonin** [comment]
Hi Zack,

The checkpoint_ssd300.pth.tar is not actually a tar archive. Just remove the .tar extension from the file name and you will be able to load it using `torch.load('checkpoint_ssd300.pth')`.

**Comment by zackdilan** [comment]
Thanks !!
