### ISSUE TITLE
Just one special class

### ISSUE THREAD

**Issue by rttariverdi67** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#69]
hi all, Thank you for this clear repository. how can I use this code and train for just one class. I want to just consider person.

thank you

**Comment by rttariverdi67** [comment]
hi all, Thank you for this clear repository. how can I use this code and train for just one class. I want to get rid of other classes except person.

thank you

**Comment by shubheshanand** [comment]
You need to change the label maps in utils.py

```
label_map = {}
label_map['background'] = 0
label_map['person'] = 1

rev_label_map = {}
rev_label_map[0] = 'background'
rev_label_map[1] = 'person'

label_color_map = {}
label_color_map['background'] = '#fffac8'
label_color_map['person'] = '#808080'

```
This should work

**Comment by rttariverdi67** [comment]
@shubheshanand thank you for your comment, I'll try it and write the results

**Comment by NiranjanRavi1993** [comment]
Hi,
     I tried the above approach and got an error in eval.py as

RuntimeError: The size of tensor a (0) must match the size of tensor b (4) at non-singleton dimension 1

There were similar issues and the solution was to find an image without a box. How do I find it? I am not able to. Would be helpful if any other way is there

**Comment by rttariverdi67** [comment]
1- do you use voc07/12 dataset?
2- are you working on all 20 classes or just some?
the answer for your question is different based on these two question

**Comment by NiranjanRavi1993** [comment]
Hi,
      1. I am using the voc07/12 dataset for training and 07 for testing. There is no error in eval.py when I train and test on all 20 classes. 
      2. When I try to train in one class, by changing the voc_labels in utils.py, the error starts showing up.  Yes, it is not able to pass the test_loader function.  In order to find the missing image, should I look into test_objects.json? It is a huge file. Any other easy way to identify the image? Thank you for your time.

**Comment by rttariverdi67** [comment]
@NiranjanRavi1993 your .json files are based on VOC2007/ImageSets/Main which contains .txt files. you can use any simple function to keep images that has your interested object (like person). in other word you need get rid of -1s in person_test.txt or person_val.txt and then write new test.txt or val.txt which is based on new person_test.txt or person_val.txt.

**Comment by NiranjanRavi1993** [comment]
@rttariverdi67  Thank you for the explanation. I was able to complete it and it started working. Both training and evaluation. Surprisingly, if I train one class, a person with a modified architecture (My changes) the AP increased more than 4%.  Would be helpful if anyone faced the same observations!
