### ISSUE TITLE
what  is the difference betwen iterations and epochs?

### ISSUE THREAD

**Issue by borre47** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#8]

**Comment by sgrvinod** [comment]
An iteration is one update to the model, i.e. one forward-backward propagation cycle, i.e. one batch's learning. 

An epoch is one pass over the entire training data, which consists of many iterations (updates to the model), depending upon how many batches the training data is split into. 

If the training data has `I` images, and the batch size is `N`, then:

There will be approximately `I // N` iterations or model updates in one epoch of training. (The exact number of iterations will be `I // N + 1`).

**Comment by borre47** [comment]
thak you
